import 'package:flutter/material.dart';

// Color constants
final Color primary = Color.fromARGB(255, 229, 130, 0);
final Color background = Color.fromARGB(255, 220, 220, 220);

// Long String Consts
final String disclaimer = 
  "Our matching algorithm is dependent on the preferences which you set in this brief survey. This includes how far you are willing to travel for your recommendations and your cuisine preferences. All data collected through the Feed Me app is used only for this recommendation engine, and is not sold to third parties or used otherwise for tracking purposes. Please try to answer honestly as your responses will be used to generate an algorithm specific to you.";

final Map<String, String> cuisines = {
  "Sicilian": "sicilian",
  "Chinese": "chinese",
  "German": "german",
  "Moroccan": "moroccan",
  "Russian": "russian",
  "South American": "south_american",
  "Asian": "asian",
  "Beerhall": "beerhall",
  "Senegalese": "senegalese",
  "Polish": "polish",
  "Hotpot": "hotpot",
  "Wraps": "wraps",
  "Vietnamese": "vietnamese",
  "Popup Restaurants": "popuprestaurants",
  "Arabian": "arabian",
  "Somali": "somali",
  "Soulfood": "soulfood",
  "Argentine": "argentine",
  "Indonesian": "indonesian",
  "Hainan": "hainan",
  "Hungarian": "hungarian",
  "Egyptian": "egyptian",
  "Honduran": "honduran",
  "Germanic": "germanic",
  "Vegan": "vegan",
  "Tacos": "tacos",
  "Catalan": "catalan",
  "Chickenshop": "chickenshop",
  "Szechuan": "szechuan",
  "Fancy": "fancy",
  "Ramen": "ramen",
  "Fast Food": "hotdogs",
  "Hong Kong Cafe": "hkcafe",
  "Bar": "bar",
  "Desserts": "desserts",
  "Malaysian": "malaysian",
  "South Asian": "south_asian",
  "Quick": "quick",
  "Poutineries": "poutineries",
  "Pizza": "pizza",
  "Italian": "italian",
  "Portuguese": "portuguese",
  "Czech": "czech",
  "Spanish": "spanish",
  "Mediterranean": "mediterranean",
  "Japanese": "japanese",
  "Pacific": "pacific",
  "Laotian": "laotian",
  "Southeast Asian": "southeast_asian",
  "Reunion": "reunion",
  "Falafel": "falafel",
  "Teppanyaki": "teppanyaki",
  "New American": "newamerican",
  "Chicken Wings": "chicken_wings",
  "Fish and Chips": "fishnchips",
  "Modern European": "modern_european",
  "Puerto Rican": "puertorican",
  "Cafeteria": "cafeteria",
  "Caribbean": "caribbean",
  "Food Court": "food_court",
  "Soup": "soup",
  "Fondue": "fondue",
  "Asian Fusion": "asianfusion",
  "Icecream": "icecream",
  "Conveyor Sushi": "conveyorsushi",
  "Comfort Food": "comfortfood",
  "Dimsum": "dimsum",
  "Gamemeat": "gamemeat",
  "Afghani": "afghani",
  "Colombian": "colombian",
  "Cajun": "cajun",
  "Latin": "latin",
  "Eastern European": "eastern_european",
  "Calabrian": "calabrian",
  "Pancakes": "pancakes",
  "Trinidadian": "trinidadian",
  "Pan Asian": "panasian",
  "French": "french",
  "Slovakian": "slovakian",
  "Armenian": "armenian",
  "Gastropubs": "gastropubs",
  "Eastern Asian": "eastern_asian",
  "Basque": "basque",
  "Steak": "steak",
  "Filipino": "filipino",
  "Uzbek": "uzbek",
  "Vegetarian": "vegetarian",
  "Turkish": "turkish",
  "British": "british",
  "Mauritius": "mauritius",
  "Tapas": "tapasmallplates",
  "American": "american",
  "New Mexican": "newmexican",
  "Mideastern": "mideastern",
  "Himalayan": "himalayan",
  "Supperclubs": "supperclubs",
  "Diners": "diners",
  "Kebab": "kebab",
  "Ethiopian": "ethiopian",
  "Mexican": "mexican",
  "Scottish": "scottish",
  "Nightfood": "nightfood",
  "Nicaraguan": "nicaraguan",
  "Buffets": "buffets",
  "Bangladeshi": "bangladeshi",
  "Western European": "western_european",
  "Gluten Free": "gluten_free",
  "Brazilian": "brazilian",
  "Australian": "australian",
  "Creperies": "creperies",
  "Tex-Mex": "tex-mex",
  "Bbq": "bbq",
  "Belgian": "belgian",
  "Bulgarian": "bulgarian",
  "Tradamerican": "tradamerican",
  "Srilankan": "srilankan",
  "Hawaiian": "hawaiian",
  "Taiwanese": "taiwanese",
  "Cheese Steaks": "cheesesteaks",
  "Eritrean": "eritrean",
  "Western": "western",
  "Raw Food": "raw_food",
  "Tuscan": "tuscan",
  "Thai": "thai",
  "Haitian": "haitian",
  "Lebanese": "lebanese",
  "Pakistani": "pakistani",
  "Dominican": "dominican",
  "Salad": "salad",
  "Canteen": "canteen",
  "Central European": "central_european",
  "Breakfast Brunch": "breakfast_brunch",
  "Indian": "indpak",
  "Scandinavian": "scandinavian",
  "Healthy": "healthy",
  "Persian": "persian",
  "Seafood": "seafood",
  "Central Asian": "central_asian",
  "Cambodian": "cambodian",
  "Irish": "irish",
  "Cafes": "cafes",
  "Japacurry": "japacurry",
  "Alcoholic": "alcoholic",
  "Peruvian": "peruvian",
  "South African": "southafrican",
  "Sushi": "sushi",
  "Singaporean": "singaporean",
  "Halal": "halal",
  "Delis": "delis",
  "Mongolian": "mongolian",
  "Cantonese": "cantonese",
  "Syrian": "syrian",
  "Foodstands": "foodstands",
  "Guamanian": "guamanian",
  "Kosher": "kosher",
  "Noodles": "noodles",
  "Salvadoran": "salvadoran",
  "Themed Cafes": "themedcafes",
  "Burgers": "burgers",
  "Sardinian": "sardinian",
  "Bakery": "bakery",
  "Waffles": "waffles",
  "Dinner Theater": "dinnertheater",
  "Sandwiches": "sandwiches",
  "Korean": "korean",
  "Georgian": "georgian",
  "European": "european",
  "Shanghainese": "shanghainese",
  "Austrian": "austrian",
  "Ukrainian": "ukrainian",
  "Brasseries": "brasseries",
  "Balkan": "balkan",
  "Southern": "southern",
  "Iberian": "iberian",
  "Polynesian": "polynesian",
  "Cuban": "cuban",
  "Central American": "central_american",
  "Izakaya": "izakaya",
  "Venezuelan": "venezuelan",
  "Tapas": "tapas",
  "Beergarden": "beergarden",
  "Greek": "greek",
  "Burmese": "burmese",
  "Czechslovakian": "czechslovakian",
  "African": "african",
  "Hotdog": "hotdog",
};